#!/bin/sh

set -e

izi_LIB_DIR=/var/lib/izi
izi_USER="izi"
izi_GROUP="izi"

case "${1}" in
    remove)
        deluser --quiet --system $izi_USER || true
        delgroup --quiet --system --only-if-empty $izi_GROUP || true
        if [ -d "$izi_LIB_DIR" ]; then
            rm -rf $izi_LIB_DIR
        fi
        ;;

    purge)
        if [ -d "$izi_LIB_DIR" ]; then
            rm -rf $izi_LIB_DIR
        fi
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

esac

#DEBHELPER#

exit 0
