#!/bin/sh

set -e

izi_CONFIGURATION_FILE=/etc/izi/izi.conf
izi_GROUP="izi"
izi_DATA_DIR=/var/lib/izi
izi_LOG_DIR=/var/log/izi
izi_USER="izi"

case "${1}" in
    configure)
        if ! getent passwd | grep -q "^izi:"; then
            adduser --system --home $izi_DATA_DIR --quiet --group $izi_USER
        fi
        # Register "$izi_USER" as a postgres user with "Create DB" role attribute
        su - postgres -c "createuser -d -R -S $izi_USER" 2> /dev/null || true
        # Configuration file
        chown $izi_USER:$izi_GROUP $izi_CONFIGURATION_FILE
        chmod 0640 $izi_CONFIGURATION_FILE
        # Log
        mkdir -p $izi_LOG_DIR
        chown $izi_USER:$izi_GROUP $izi_LOG_DIR
        chmod 0750 $izi_LOG_DIR
        # Data dir
        chown $izi_USER:$izi_GROUP $izi_DATA_DIR
        ;;
    *)
        ;;
esac

#DEBHELPER#

exit 0
